# Generated by Django 3.2.8 on 2023-04-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230413_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
